### ISSUE TITLE
paged, sorted, filtered results have duplicate results in subsequent pages

### ISSUE THREAD

**Issue by coupster74** [TriPSs/nestjs-query#162] opened 2023-08-04 22:24 UTC
**Describe the bug**

This is a complex one. I have a query which uses sorting, a filter against a child entity, and paging. Under these conditions, duplicate results can be found in multiple page sets. 

**To Reproduce**
Really difficult to reproduce, but will demonstrate the scenario. I execute the following query and run a countOccurances on the results. 

This query: 
```graphql 
 query Actions(
              $paging: CursorPaging
              $filter: ActionFilter
              $sorting: [ActionSort!]!
            ) {
              actions(paging: $paging, filter: $filter, sorting: $sorting) {
                pageInfo {
                  endCursor
                  hasNextPage
                }
                totalCount
                edges {
                  node {
                    id
                    title
                    
                  }
                }
              }
            }
          `,
          variables: {
            paging: {
              first: 50,
              after: cursor,
            },
            filter: {
              tactic: { protest: { is: true } },
              date: {
                between: {
                  lower: from.toISOString(),
                  upper: to.toISOString(),
                },
              },
            },
            sorting: [
              {
                field: "date",
                direction: "ASC",
              },
            ],
          },
```
returns the following: 
<img width="435" alt="image" src="https://github.com/TriPSs/nestjs-query/assets/6988322/b954d8dd-ed6a-40fa-a02c-b0a16fadbabc">

however, if I remove the tactic filter, the offending row only occurs once. And if I leave in the tactic, but remove the sort the offending row only occurs once. If I change the paging to load 1000 (my results are only ~200 rows), then the offending row only occurs once. 

**Expected behavior**
in this scenario, no rows should be reoccur in subsequent pages

**Desktop (please complete the following information):**
 - Node Version : v18.14
 - Nestjs-query Version : 4.0.0
 
Note: I'm also configured using typeorm on postgres

**Comment by TriPSs** [comment] 2023-08-05 09:10
Would it be possible to create a example repo which has this issue?  Or create a test case that reproduces it, not sure if this is possible since you mentioned it's hard to reproduce but I think we do need something If we want to tackle this.

**Comment by TriPSs** [comment] 2024-04-18 08:38
Closing this, if still an issue please add a test case and re-open.

**Closed by TriPSs** 2024-04-18 08:38 UTC
Labels: bug, more info needed

**Comment by coupster74** [comment] 2025-03-31 21:32
@TriPSs would like to reopen as this is still happening. We will attempt to recreate.

**Comment by coupster74** [comment] 2025-03-31 22:14
@TriPSs Follow up.. 

i was curious if the issue was related to a string. I added a string representation of protest as protest2 and tested if {protest2: { eq: 'true' }}. This did not resolve the issue, which got me thinking it is less to do with the filter hander (eq vs is) and more about the relationship itself. 

So I attempted to change @FilterableRelation to @FilterableUnPagedRelation for tactic and then it worked fine. 

However, since the relationship is a many to one (and not a many to many), the idea that we have a filterableUnPagedRelationship never made sense to use. 

As mentioned, the data seeding requirements etc make creating a repo to recreate this quite difficult.. anything you can see in the @FilterableRelation related to a test and a sort which jumps out to you?

**Comment by coupster74** [comment] 2025-04-02 13:42
@TriPSs I have figured it out. 

The issue is not related to relations, this changed the results of what was returned and I no longer had an issue. 

the issue is actually a result of sorting by a date column where multiple rows have the same data value. PostgreSQL chooses an arbitrary order among rows with identical date values — which can change between queries, leading to:

- Duplicates across pages
- Missing rows

This is not a bug — it's expected behavior when the sort order doesn't produce a total order (apparently). 

I have a created date column which is more unique (defaulted to now() function) so a sort which is based on the original date AND the created date fixes the issue.
